### ISSUE TITLE
Support for GGSearch

### ISSUE THREAD

**Issue by GGLVXD** [Extravi/araa-search#141]
Add support for https://ggsearch.eu.org for more results

**Comment by amogusussy** [comment]
The project doesn't currently have any way of adding new search engines.
Also, ggsearch is just a metasearch engine, so it aggregates results from other engines (e.g. bing, google, ddg, etc). It would make more sense to scrape the results ourselves, rather than using a proxy engine (ggsearch) for results on another proxy engine (araa).
There has previously been some work to expand the project to support more than one engine (see #106 ), but its been open for over half a year, so I doubt it'll be done any time soon.

**Comment by Extravi** [comment]
> The project doesn't currently have any way of adding new search engines.
> Also, ggsearch is just a metasearch engine, so it aggregates results from other engines (e.g. bing, google, ddg, etc). It would make more sense to scrape the results ourselves, rather than using a proxy engine (ggsearch) for results on another proxy engine (araa).
> There has previously been some work to expand the project to support more than one engine (see #106 ), but its been open for over half a year, so I doubt it'll be done any time soon.

"It would make more sense to scrape the results ourselves" agree as it would be much more reliable and faster I want to add other engines like. I want but I would want to code the fallback part myself

**Comment by Extravi** [comment]
we should look into adding other engines again to make Araa more reliable I have a good idea for a fallback system

**Comment by Extravi** [comment]
@amogusussy do you have discord?

**Comment by amogusussy** [comment]
> @amogusussy do you have discord?

No. I don't use any online chat services, but I can make a matrix account.

**Comment by Extravi** [comment]
> > @amogusussy do you have discord?
> 
> No. I don't use any online chat services, but I can make a matrix account.

alright I'll make an account later
