### ISSUE TITLE
Privacy Policy?

### ISSUE THREAD

**Issue by Ramenu** [Extravi/araa-search#156]
I couldn't find any links to one. Perhaps this could be added for the sake of transparency?

**Comment by Extravi** [comment]
someone had asked me this question via email and this was my response

"Hello, I don't personally log anything; all logs are sent to /dev/null because Araa depends on an Nginx proxy pass, so I don't have a log of search queries or IP addresses. Also, it isn't possible for me to even see the IP addresses of users since Araa's search is behind a Cloudflare proxy. However, Cloudflare might collect some basic analytics that I can see, such as geolocation and request count, like how many people are using it from Canada or the USA and the number of requests from each country. Still, I cannot see the request or the IP address of any user, so I cannot see any identifiable information. However, I am not sure what data Cloudflare's proxy retains and for how long, but considering Cloudflare isn't an advertising company and they are a security company, I don't necessarily see it as a privacy issue. I use their proxy to make Araa search faster for users and more reliable and resistant against bots because I don't have the necessary resources or infrastructure to handle this all myself."

**Comment by Ramenu** [comment]
Thank you! Maybe just add in a page elaborating on this in the future so people don't ask the same question again. But if not, that's ok too. :)
