### ISSUE TITLE
Clarification on .env File Usage in docker-compose.yml

### ISSUE THREAD

**Issue by tiritibambix** [Extravi/araa-search#167]
Hello there!

I recently came across Araa and thought it looked really promising, so I really wanted to give it a try.

As a Docker and Portaier user and a casual hobbyist when it comes to self-hosting, I hope it's okay to ask a question.

While I was exploring the [docker-compose.yml](https://github.com/Extravi/araa-search/blob/main/compose.yaml) file, I noticed this comment:
```
    env_file:
      - .env # May be redundant. Who cares ¯\_(ツ)_/¯
```
I'm a bit puzzled about what that means. Do I need to set up variables through the [.env](https://github.com/Extravi/araa-search/blob/main/.env) file, or is it not necessary? Would it be possible for me to add some of those variables directly into the docker-compose.yml by including:
```
   environment:
      - PORT=8000
      - WORKERS=8
      - THREADS=2
      - .....
```
I couldn't find any information about variables in the [documentation](https://extravi.dev/araa) linked in the readme, so I'm feeling a little uncertain about the next steps.

Thanks so much for your help!

**Comment by TEMtheLEM** [comment]
The line is "redundant" because, from what I understand, the `.env` file will be loaded by default with compose. I put that line there to explicitly state that compose should load the `.env` file.

The comment could've been written better to explain this. That's my bad, I'll update it.

Also, you are correct in that you don't necessarily need the file. Your way of putting variables inside of `compose.yml` should work just fine.

As for documentation on the env. vars that are recognized, look at https://hub.docker.com/r/temthelem/araa-search

While I'm at it; @Extravi could you possibly put that link in the docs for future users?

**Comment by tiritibambix** [comment]
Thanks a lot for the clarifications. It's working great!

Last question: where are my preferences saved ? In my cookies ? If so, shouldn't I get a complex url somewhere to copy to other browsers / machines if I need to ?

**Comment by TEMtheLEM** [comment]
The user settings (such as themes, lang, etc) are stored as cookies.

At the moment, there's no built-in way to generate a URL to transfer the settings from one browser/device to another. That's a pretty good idea, though!

**Comment by tiritibambix** [comment]
Thank you for your answer. I hope this is a feature that will be implemented one day :)
